---
#####################################
#    Save various configurations.   #
#####################################
# To be run after everything has been installed.
- name: Save various configurations
  hosts: "{{ target_group }}"
  vars_files:
    - variables.yml
  become: yes

  tasks:
    - name: Add admin user for Matomo panel and phpMyAdmin to htpasswd file
    # Set up basic auth user/password for web access to Matomo panel and phpMyAdmin.
      community.general.htpasswd:
        path: /etc/nginx/.web_htpasswd
        name: "{{ web_username }}"
        password: "{{ web_user_password }}"
        owner: root
        group: www-data
        mode: '0640'

    - name: Remove existing matomo_domain site configuration file if it exists
      # Delete conf files if they are left over from maybe earlier unsuccessful runs of the playbook.
      # They will be re-created below.
      file:
        path: "/etc/nginx/sites-enabled/{{ matomo_domain }}.conf"
        state: absent
      become: yes

    - name: Create symlink for phpMyAdmin in web root
      file:
        src: /usr/share/phpmyadmin
        dest: /var/www/html/pma
        state: link
        mode: '0775'

    - name: Allow nginx user (www-data) to traverse /usr and /usr/share
      ansible.posix.acl:
        path: "{{ item }}"
        entity: www-data
        etype: user
        permissions: x
        state: present
      loop:
        - /usr
        - /usr/share

    - name: Allow nginx user to access phpMyAdmin via ACL
      ansible.posix.acl:
        path: /usr/share/phpmyadmin
        entity: www-data
        etype: user
        permissions: rx
        state: present
        recurse: yes

    # Nginx virtual host templates - Matomo plus GeoIP2 configuration.
    - name: Save GeoIP2 config
      template:
        src: geoip2.conf.j2
        dest: /etc/nginx/sites-available/geoip2.conf

    - name: Add GeoIP2 to nginx configuration
      file:
        src: /etc/nginx/sites-available/geoip2.conf
        dest: /etc/nginx/sites-enabled/geoip2.conf
        state: link

    - name: Save matomo config
      template:
        src: nginx_matomo_geoip2.conf.j2
        dest: /etc/nginx/sites-available/matomo.conf

    - name: Enable matomo site
      file:
        src: /etc/nginx/sites-available/matomo.conf
        dest: /etc/nginx/sites-enabled/matomo.conf
        state: link
