---
- name: Install and configure PostgreSQL
  hosts: django_servers
  become: yes
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Install PostgreSQL
      apt:
        name:
          - postgresql
          - postgresql-contrib
        state: present
    - name: Ensure PostgreSQL is running
      service:
        name: postgresql
        state: started
        enabled: yes
    - name: Install pip and psycopg2 dependencies for Ansible PostgreSQL modules
      apt:
        name:
          - python3-pip
          - python3-psycopg2
        state: present
    - name: Create database user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
    - name: Create database
      become_user: postgres
      community.postgresql.postgresql_db:
        name: "{{ db_name }}"
        owner: "{{ db_user }}"
        state: present
