---
- name: Install prerequisites
  hosts: django_servers
  become: yes
  gather_facts: no
  vars_files:
    - variables.yml
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install required packages
      apt:
        name:
          - git
          - build-essential
          - curl
          - fail2ban
          - libpq-dev
          - python3-pip
          - software-properties-common
          - ca-certificates
          - unzip
          - wget
          - gnupg
          - libmaxminddb-dev
          - libmaxminddb0
          - mmdb-bin
          - libpcre3
          - libpcre3-dev
          - zlib1g-dev
          - libssl-dev
          - lsb-release
          - apt-transport-https
          - acl
        state: present
    - name: Ensure fail2ban is running
      service:
        name: fail2ban
        state: started
        enabled: yes
    - name: Ensure application group exists
      group:
        name: "{{ web_group }}"
        state: present
    - name: Ensure application user exists
      user:
        name: "{{ web_user }}"
        group: "{{ web_group }}"
        shell: /bin/bash
        password_lock: yes
        create_home: yes
        state: present
    - name: Ensure Django app directory is owned by application user/group
      file:
        path: "{{ django_app_dir }}"
        owner: "{{ web_user }}"
        group: "{{ web_group }}"
        state: directory
        recurse: yes
